global using static System.Net.Mime.MediaTypeNames;
global using BuildingBlocks.Exceptions;
global using Todo.Application.Dtos;
global using BuildingBlocks.CQRS;
global using FluentValidation;
global using Todo.Domain.Interfaces;
global using Todo.Application.Mappings;
global using Todo.Application.Query.Get;
global using BuildingBlocks.Behaviors;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;